<?php
$page_title       = 'Cookies & Analytics Notice | Direct Property Buyer';
$page_description = 'Cookies & Analytics Notice for Direct Property Buyer. Final wording to be confirmed before launch.';
$page_slug        = 'cookies-analytics';
require __DIR__ . '/includes/head.php';
require __DIR__ . '/includes/header.php';
?>
<main id="app"><section class="relative bg-navy overflow-hidden"><div class="absolute inset-0"><img src="https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1700&q=80" onerror="this.onerror=null;this.src='https://placehold.co/1200x800/0B1F2A/C49A5A?text=Direct+Property+Buyer'" class="w-full h-full object-cover" alt=""></div><div class="absolute inset-0 overlay-grad"></div><div class="relative max-w-7xl mx-auto px-6 pt-16 pb-14 md:pt-24 md:pb-20"><nav class="text-xs text-ivory/55 mb-5 flex items-center gap-2 flex-wrap"><a href="index.php" data-link class="hover:text-gold-soft">Home</a> <span>›</span> <span class="text-ivory/80">Cookies & Analytics Notice</span></nav><div class="mb-5"><span class="eyebrow light">Information</span></div><h1 class="font-display text-white text-[2.2rem] sm:text-4xl lg:text-[3.1rem] leading-[1.08] max-w-3xl mb-5">Cookies & Analytics Notice</h1><p class="text-ivory/85 text-lg leading-relaxed max-w-2xl mb-8">This page will be finalised during the build stage. The demo focuses on design, structure and the user journey.</p><div class="flex flex-wrap gap-3"><a href="contact.php" data-link class="btn btn-gold">Request a Free Property Assessment</a><a href="https://wa.me/61421300305?text=Hi%20Direct%20Property%20Buyer%2C%20I'd%20like%20a%20free%2C%20no-obligation%20property%20assessment." target="_blank" rel="noopener" class="btn btn-light">Message Us on WhatsApp</a></div></div></section><section class="py-20 bg-ivory"><div class="max-w-3xl mx-auto px-6 text-center reveal"><p class="text-ink/70 mb-8">Final wording for Cookies & Analytics Notice will be prepared with you before launch. In the meantime, you can return home or get in touch.</p><div class="flex flex-wrap gap-3 justify-center"><a href="index.php" data-link class="btn btn-gold">Back to Home</a><a href="contact.php" data-link class="btn btn-outline">Contact</a></div></div></section></main>
<?php require __DIR__ . '/includes/footer.php'; ?>
