<?php
$page_title       = 'Cookies & Analytics Notice | Direct Property Buyer';
$page_description = 'How Direct Property Buyer uses cookies, analytics tools, tracking pixels and similar technologies on this website, and how you can manage them.';
$page_slug        = 'cookies-analytics';
require __DIR__ . '/includes/head.php';
require __DIR__ . '/includes/header.php';
?>
<main id="app"><section class="relative bg-navy overflow-hidden"><div class="absolute inset-0"><img src="https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1700&q=80" onerror="this.onerror=null;this.src='https://placehold.co/1200x800/0B1F2A/C49A5A?text=Direct+Property+Buyer'" class="w-full h-full object-cover" alt=""></div><div class="absolute inset-0 overlay-grad"></div><div class="relative max-w-7xl mx-auto px-6 pt-16 pb-14 md:pt-24 md:pb-20"><nav class="text-xs text-ivory/55 mb-5 flex items-center gap-2 flex-wrap"><a href="index.php" data-link class="hover:text-gold-soft">Home</a> <span>&rsaquo;</span> <span class="text-ivory/80">Cookies &amp; Analytics Notice</span></nav><div class="mb-5"><span class="eyebrow light">Information</span></div><h1 class="font-display text-white text-[2.2rem] sm:text-4xl lg:text-[3.1rem] leading-[1.08] max-w-3xl mb-5">Cookies &amp; Analytics Notice</h1><p class="text-ivory/85 text-lg leading-relaxed max-w-2xl mb-8">This notice explains how Direct Property Buyer may use cookies, analytics tools, tracking pixels and similar technologies on this website, and how you can manage them.</p><div class="flex flex-wrap gap-3"><a href="contact.php" data-link class="btn btn-gold">Request a Free Property Assessment</a><a href="https://wa.me/0421300305?text=Hi%20Direct%20Property%20Buyer%2C%20I'd%20like%20a%20free%2C%20no-obligation%20property%20assessment." target="_blank" rel="noopener" class="btn btn-light">Message Us on WhatsApp</a></div></div></section>

<section class="py-16 md:py-20 bg-ivory"><div class="max-w-3xl mx-auto px-6">

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">1. About This Notice</h2><p class="text-ink/75 leading-relaxed mb-4">This Cookies &amp; Analytics Notice explains how Direct Property Buyer may use cookies, analytics tools, tracking pixels and similar technologies on this website.</p><p class="text-ink/75 leading-relaxed">Cookies are small files or pieces of information stored on your browser or device when you visit a website. They help websites function properly, remember preferences, understand visitor behaviour and improve user experience.</p></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">2. How We Use Cookies &amp; Analytics</h2><p class="text-ink/75 leading-relaxed mb-5">Direct Property Buyer may use cookies, analytics tools and similar technologies to:</p><ul class="space-y-3 list-none">
<li class="flex gap-3"><i class="fa-solid fa-check text-gold-soft text-xs mt-1.5 shrink-0"></i><span class="text-ink/75 leading-relaxed">Operate and secure the website.</span></li>
<li class="flex gap-3"><i class="fa-solid fa-check text-gold-soft text-xs mt-1.5 shrink-0"></i><span class="text-ink/75 leading-relaxed">Understand how visitors use the website.</span></li>
<li class="flex gap-3"><i class="fa-solid fa-check text-gold-soft text-xs mt-1.5 shrink-0"></i><span class="text-ink/75 leading-relaxed">Improve website performance and usability.</span></li>
<li class="flex gap-3"><i class="fa-solid fa-check text-gold-soft text-xs mt-1.5 shrink-0"></i><span class="text-ink/75 leading-relaxed">Measure which pages, guides and services are useful.</span></li>
<li class="flex gap-3"><i class="fa-solid fa-check text-gold-soft text-xs mt-1.5 shrink-0"></i><span class="text-ink/75 leading-relaxed">Improve SEO, AEO and GEO performance.</span></li>
<li class="flex gap-3"><i class="fa-solid fa-check text-gold-soft text-xs mt-1.5 shrink-0"></i><span class="text-ink/75 leading-relaxed">Understand how people find the website.</span></li>
<li class="flex gap-3"><i class="fa-solid fa-check text-gold-soft text-xs mt-1.5 shrink-0"></i><span class="text-ink/75 leading-relaxed">Measure the effectiveness of marketing campaigns.</span></li>
<li class="flex gap-3"><i class="fa-solid fa-check text-gold-soft text-xs mt-1.5 shrink-0"></i><span class="text-ink/75 leading-relaxed">Improve future content, advertising and lead generation.</span></li>
<li class="flex gap-3"><i class="fa-solid fa-check text-gold-soft text-xs mt-1.5 shrink-0"></i><span class="text-ink/75 leading-relaxed">Help show relevant content or advertising to people who have visited the website.</span></li>
</ul></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">3. Types of Cookies &amp; Tracking We May Use</h2><ol class="space-y-3 list-none">
<li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">3.1</span><span class="text-ink/75 leading-relaxed"><strong class="text-navy font-semibold">Essential cookies.</strong> These help the website work properly, including page loading, forms, security and basic website functionality.</span></li>
<li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">3.2</span><span class="text-ink/75 leading-relaxed"><strong class="text-navy font-semibold">Analytics cookies.</strong> These help us understand website traffic, visitor behaviour, popular pages, referral sources and website performance. This may include tools such as Google Analytics or similar analytics platforms.</span></li>
<li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">3.3</span><span class="text-ink/75 leading-relaxed"><strong class="text-navy font-semibold">Marketing and remarketing cookies.</strong> These may help us understand whether marketing campaigns are working and may allow us to show relevant advertising to people who have previously visited the website. This may include tools such as Meta Pixel, Google Ads tracking or similar platforms.</span></li>
<li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">3.4</span><span class="text-ink/75 leading-relaxed"><strong class="text-navy font-semibold">Performance cookies.</strong> These help us identify technical issues, improve page speed, monitor errors and improve the user experience.</span></li>
</ol></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">4. Third-Party Platforms</h2><p class="text-ink/75 leading-relaxed">We may use third-party platforms such as Google, Meta, analytics providers, advertising platforms, website hosting providers, form tools, email tools or other digital service providers. These providers may collect or process information in accordance with their own privacy policies and terms.</p></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">5. Information That May Be Collected</h2><p class="text-ink/75 leading-relaxed mb-4">Depending on your browser settings and how you use the website, cookies and analytics tools may collect information such as pages visited, time spent on the website, device and browser type, approximate location, referral source, clicks and interactions, form activity, advertising campaign source, IP address or similar online identifiers.</p><p class="text-ink/75 leading-relaxed">If you submit an enquiry form, we may also collect the personal information you provide, such as your name, phone number, email address, property suburb, property details and enquiry message.</p></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">6. Managing or Blocking Cookies</h2><p class="text-ink/75 leading-relaxed">You can manage or block cookies through your browser settings. If you disable cookies, some parts of the website may not function properly.</p></div>

<div class="reveal mb-12"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">7. Relationship to Our Privacy Policy</h2><p class="text-ink/75 leading-relaxed">This notice should be read together with our <a href="privacy-policy.php" data-link class="text-gold-dark font-semibold hover:text-gold underline decoration-gold/40 underline-offset-2">Privacy Policy</a>, which explains how we collect, use, store and handle the personal information you share with us.</p></div>

<div class="reveal border-t border-ink/10 pt-8"><p class="text-ink/70 leading-relaxed mb-6">If you have any questions about how we use cookies and analytics, please get in touch and a member of our team will be happy to help.</p><div class="flex flex-wrap gap-3"><a href="contact.php" data-link class="btn btn-gold">Contact Us</a><a href="index.php" data-link class="btn btn-outline">Back to Home</a></div></div>

</div></section></main>
<?php require __DIR__ . '/includes/footer.php'; ?>