<?php
$page_title       = 'Disclaimer | Direct Property Buyer';
$page_description = 'The information on the Direct Property Buyer website is general in nature only and is not legal, financial, tax, lending or property advice. Please obtain independent professional advice before acting.';
$page_slug        = 'disclaimer';
require __DIR__ . '/includes/head.php';
require __DIR__ . '/includes/header.php';
?>
<main id="app"><section class="relative bg-navy overflow-hidden"><div class="absolute inset-0"><img src="https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1700&q=80" onerror="this.onerror=null;this.src='https://placehold.co/1200x800/0B1F2A/C49A5A?text=Direct+Property+Buyer'" class="w-full h-full object-cover" alt=""></div><div class="absolute inset-0 overlay-grad"></div><div class="relative max-w-7xl mx-auto px-6 pt-16 pb-14 md:pt-24 md:pb-20"><nav class="text-xs text-ivory/55 mb-5 flex items-center gap-2 flex-wrap"><a href="index.php" data-link class="hover:text-gold-soft">Home</a> <span>&rsaquo;</span> <span class="text-ivory/80">Disclaimer</span></nav><div class="mb-5"><span class="eyebrow light">Information</span></div><h1 class="font-display text-white text-[2.2rem] sm:text-4xl lg:text-[3.1rem] leading-[1.08] max-w-3xl mb-5">Disclaimer</h1><p class="text-ivory/85 text-lg leading-relaxed max-w-2xl mb-8">The information on this website is general in nature only. It is not legal, financial, tax, lending or property advice, and should not be relied on in place of independent professional advice for your own situation.</p><div class="flex flex-wrap gap-3"><a href="contact.php" data-link class="btn btn-gold">Request a Free Property Assessment</a><a href="https://wa.me/0421300305?text=Hi%20Direct%20Property%20Buyer%2C%20I'd%20like%20a%20free%2C%20no-obligation%20property%20assessment." target="_blank" rel="noopener" class="btn btn-light">Message Us on WhatsApp</a></div></div></section>

<section class="py-16 md:py-20 bg-ivory"><div class="max-w-3xl mx-auto px-6">

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">1. About This Website</h2><p class="text-ink/75 leading-relaxed">This website is operated by Direct Property Buyer. The information on this website, including property guides, articles, FAQs, comparison tables, service pages and general commentary, is provided for general information purposes only. It reflects general opinion and practical property experience and should not be relied on as legal, financial, tax, lending, investment, accounting, real estate, building, planning or valuation advice.</p></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">2. General Information Only</h2><p class="text-ink/75 leading-relaxed">Every property, owner and personal situation is different. Before making any decision about selling, buying, renovating, refinancing, transferring, investing in, or entering into any arrangement involving property, you should obtain independent advice from appropriately qualified professionals. This may include a solicitor, conveyancer, accountant, financial adviser, mortgage broker, licensed estate agent, buyer&rsquo;s advocate, building consultant, town planner or tax adviser.</p></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">3. No Adviser&ndash;Client Relationship</h2><p class="text-ink/75 leading-relaxed">Nothing on this website creates a professional adviser-client relationship. Any information provided through the website is general in nature and does not take into account your personal objectives, financial position, legal obligations, tax position, property ownership structure, mortgage position, family circumstances or future plans.</p></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">4. Estimates, Offers &amp; Expected Outcomes</h2><p class="text-ink/75 leading-relaxed">Any reference to potential sale value, renovation uplift, direct offers, property takeover options, investment opportunities, settlement timeframes, savings, returns, or expected outcomes is general only. Actual outcomes depend on many factors, including property condition, location, market demand, legal title, finance, building issues, planning requirements, buyer interest, timing and market conditions.</p></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">5. No Guarantees</h2><p class="text-ink/75 leading-relaxed">Direct Property Buyer does not guarantee that any property will sell, be purchased, achieve a particular price, obtain finance, be suitable for renovation, produce a profit, or meet a particular timeframe.</p></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">6. Property Solution Options</h2><ol class="space-y-3 list-none"><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">6.1</span><span class="text-ink/75 leading-relaxed">Direct Property Buyer may, where suitable, discuss direct purchase, as-is sale, renovation-before-sale, property takeover, referral, project coordination or other property solution options.</span></li><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">6.2</span><span class="text-ink/75 leading-relaxed">Any offer, proposal or arrangement is subject to assessment, due diligence, written agreement and, where relevant, independent professional advice.</span></li></ol></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">7. No Obligation</h2><p class="text-ink/75 leading-relaxed">You are under no obligation to accept any proposal or proceed with any service.</p></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">8. Licensed &amp; Qualified Professionals</h2><ol class="space-y-3 list-none"><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">8.1</span><span class="text-ink/75 leading-relaxed">Where a service requires a licensed estate agent, buyer&rsquo;s advocate, conveyancer, legal practitioner, financial adviser, mortgage broker or other regulated professional, Direct Property Buyer will either refer you to, work with, or recommend that you obtain advice from an appropriately licensed or qualified professional.</span></li><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">8.2</span><span class="text-ink/75 leading-relaxed">Direct Property Buyer does not provide legal, conveyancing, financial, lending, tax or accounting advice.</span></li></ol></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">9. Investment &amp; Joint Venture Opportunities</h2><ol class="space-y-3 list-none"><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">9.1</span><span class="text-ink/75 leading-relaxed">Any information about investment opportunities, joint ventures, co-investment, property-backed arrangements or similar opportunities is general information only. It is not financial advice, investment advice, a recommendation, a guarantee, or an offer to the public.</span></li><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">9.2</span><span class="text-ink/75 leading-relaxed">Any investment or joint venture arrangement must be considered carefully and should only proceed after independent legal, financial and tax advice, due diligence, and written agreement between the parties.</span></li></ol></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">10. Third-Party Links</h2><p class="text-ink/75 leading-relaxed">This website may contain links to external websites, third-party platforms or service providers. Direct Property Buyer is not responsible for the content, accuracy, privacy practices or conduct of third-party websites or providers.</p></div>

<div class="reveal mb-12"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">11. Accuracy of Information</h2><p class="text-ink/75 leading-relaxed">We aim to keep website information accurate and up to date, but property markets, laws, lending rules, tax treatment and government requirements can change. We do not warrant that all information on this website is complete, current or suitable for your specific circumstances.</p></div>

<div class="reveal border-t border-ink/10 pt-8"><p class="text-ink/70 leading-relaxed mb-6">If you have any questions about this disclaimer, or you&rsquo;d like to talk through your options with no obligation, our team is happy to help.</p><div class="flex flex-wrap gap-3"><a href="contact.php" data-link class="btn btn-gold">Contact Us</a><a href="index.php" data-link class="btn btn-outline">Back to Home</a></div></div>

</div></section></main>
<?php require __DIR__ . '/includes/footer.php'; ?>