<?php
$page_title       = 'Privacy Policy | Direct Property Buyer';
$page_description = 'How Direct Property Buyer collects, uses and protects the confidential information you share with us.';
$page_slug        = 'privacy-policy';
require __DIR__ . '/includes/head.php';
require __DIR__ . '/includes/header.php';
?>
<main id="app"><section class="relative bg-navy overflow-hidden"><div class="absolute inset-0"><img src="https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1700&q=80" onerror="this.onerror=null;this.src='https://placehold.co/1200x800/0B1F2A/C49A5A?text=Direct+Property+Buyer'" class="w-full h-full object-cover" alt=""></div><div class="absolute inset-0 overlay-grad"></div><div class="relative max-w-7xl mx-auto px-6 pt-16 pb-14 md:pt-24 md:pb-20"><nav class="text-xs text-ivory/55 mb-5 flex items-center gap-2 flex-wrap"><a href="index.php" data-link class="hover:text-gold-soft">Home</a> <span>›</span> <span class="text-ivory/80">Privacy Policy</span></nav><div class="mb-5"><span class="eyebrow light">Information</span></div><h1 class="font-display text-white text-[2.2rem] sm:text-4xl lg:text-[3.1rem] leading-[1.08] max-w-3xl mb-5">Privacy Policy</h1><p class="text-ivory/85 text-lg leading-relaxed max-w-2xl mb-8">Direct Property Buyer is committed to maintaining the confidentiality and security of our clients&rsquo; information. This policy outlines how we handle and protect the confidential information you share with us.</p><div class="flex flex-wrap gap-3"><a href="contact.php" data-link class="btn btn-gold">Request a Free Property Assessment</a><a href="https://wa.me/61421300305?text=Hi%20Direct%20Property%20Buyer%2C%20I'd%20like%20a%20free%2C%20no-obligation%20property%20assessment." target="_blank" rel="noopener" class="btn btn-light">Message Us on WhatsApp</a></div></div></section>

<section class="py-16 md:py-20 bg-ivory"><div class="max-w-3xl mx-auto px-6">

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">1. Introduction</h2><p class="text-ink/75 leading-relaxed">Direct Property Buyer is committed to maintaining the confidentiality and security of our clients&rsquo; information. This policy outlines how we handle and protect confidential information.</p></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">2. Definition of Confidential Information</h2><p class="text-ink/75 leading-relaxed">Confidential information includes any personal, financial, or business-related information provided by clients during the course of our services.</p></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">3. Use of Confidential Information</h2><ol class="space-y-3 list-none"><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">3.1</span><span class="text-ink/75 leading-relaxed">Confidential information will be used solely for the purpose of providing our services.</span></li><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">3.2</span><span class="text-ink/75 leading-relaxed">We will not disclose confidential information to any third parties without the client&rsquo;s consent, except as required by law.</span></li></ol></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">4. Protection of Confidential Information</h2><ol class="space-y-3 list-none"><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">4.1</span><span class="text-ink/75 leading-relaxed">We implement appropriate security measures to protect confidential information from unauthorised access, use, or disclosure.</span></li><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">4.2</span><span class="text-ink/75 leading-relaxed">Confidential information will be stored in trusted cloud storage services, such as Google Drive or Dropbox, which comply with Australian data protection laws.</span></li></ol></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">5. Client Rights</h2><ol class="space-y-3 list-none"><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">5.1</span><span class="text-ink/75 leading-relaxed">Clients have the right to access their confidential information and request corrections if necessary.</span></li><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">5.2</span><span class="text-ink/75 leading-relaxed">Clients can request the deletion of their confidential information, subject to legal and contractual obligations.</span></li></ol></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">6. Breach of Confidentiality</h2><ol class="space-y-3 list-none"><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">6.1</span><span class="text-ink/75 leading-relaxed">Any breach of confidentiality will be taken seriously and addressed promptly.</span></li><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">6.2</span><span class="text-ink/75 leading-relaxed">Clients will be notified of any breaches that may affect their confidential information.</span></li></ol></div>

<div class="reveal mb-12"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">7. Amendments</h2><ol class="space-y-3 list-none"><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">7.1</span><span class="text-ink/75 leading-relaxed">Direct Property Buyer reserves the right to amend this confidentiality policy at any time.</span></li><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">7.2</span><span class="text-ink/75 leading-relaxed">Clients will be notified of any changes via our website.</span></li></ol></div>

<div class="reveal border-t border-ink/10 pt-8"><p class="text-ink/70 leading-relaxed mb-6">If you have any questions about how we handle your information, please get in touch and a member of our team will be happy to help.</p><div class="flex flex-wrap gap-3"><a href="contact.php" data-link class="btn btn-gold">Contact Us</a><a href="index.php" data-link class="btn btn-outline">Back to Home</a></div></div>

</div></section></main>
<?php require __DIR__ . '/includes/footer.php'; ?>