<?php
$page_title       = 'Terms of Use | Direct Property Buyer';
$page_description = 'Terms of Use for Direct Property Buyer covering our services, client obligations, fees, investment opportunities and more.';
$page_slug        = 'terms';
require __DIR__ . '/includes/head.php';
require __DIR__ . '/includes/header.php';
?>
<main id="app"><section class="relative bg-navy overflow-hidden"><div class="absolute inset-0"><img src="https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1700&q=80" onerror="this.onerror=null;this.src='https://placehold.co/1200x800/0B1F2A/C49A5A?text=Direct+Property+Buyer'" class="w-full h-full object-cover" alt=""></div><div class="absolute inset-0 overlay-grad"></div><div class="relative max-w-7xl mx-auto px-6 pt-16 pb-14 md:pt-24 md:pb-20"><nav class="text-xs text-ivory/55 mb-5 flex items-center gap-2 flex-wrap"><a href="index.php" data-link class="hover:text-gold-soft">Home</a> <span>›</span> <span class="text-ivory/80">Terms of Use</span></nav><div class="mb-5"><span class="eyebrow light">Information</span></div><h1 class="font-display text-white text-[2.2rem] sm:text-4xl lg:text-[3.1rem] leading-[1.08] max-w-3xl mb-5">Terms of Use</h1><p class="text-ivory/85 text-lg leading-relaxed max-w-2xl mb-8">By accessing or using our services, you agree to comply with and be bound by the following terms and conditions. Please read them carefully.</p><div class="flex flex-wrap gap-3"><a href="contact.php" data-link class="btn btn-gold">Request a Free Property Assessment</a><a href="https://wa.me/0421300305?text=Hi%20Direct%20Property%20Buyer%2C%20I'd%20like%20a%20free%2C%20no-obligation%20property%20assessment." target="_blank" rel="noopener" class="btn btn-light">Message Us on WhatsApp</a></div></div></section>

<section class="py-16 md:py-20 bg-ivory"><div class="max-w-3xl mx-auto px-6">

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">1. Introduction</h2><p class="text-ink/75 leading-relaxed">Welcome to Direct Property Buyer. By accessing or using our services, you agree to comply with and be bound by the following terms and conditions. Please read them carefully.</p></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">2. Services Provided</h2><p class="text-ink/75 leading-relaxed">Direct Property Buyer specialises in property investment, renovation, and sales. We offer services to help homeowners unlock the full potential of their properties.</p></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">3. Client Obligations</h2><ol class="space-y-3 list-none"><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">3.1</span><span class="text-ink/75 leading-relaxed">Clients must provide accurate and complete information when engaging our services.</span></li><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">3.2</span><span class="text-ink/75 leading-relaxed">Clients agree to comply with all applicable laws and regulations.</span></li><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">3.3</span><span class="text-ink/75 leading-relaxed">Clients must not use our services for any unlawful or prohibited activities.</span></li></ol></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">4. Fees and Payments</h2><ol class="space-y-3 list-none"><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">4.1</span><span class="text-ink/75 leading-relaxed">All fees for our services will be clearly outlined in the service agreement.</span></li><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">4.2</span><span class="text-ink/75 leading-relaxed">Payments must be made according to the agreed schedule.</span></li><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">4.3</span><span class="text-ink/75 leading-relaxed">Late payments may incur additional charges.</span></li></ol></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">5. Investment Opportunities</h2><p class="text-ink/75 leading-relaxed mb-6">We offer high-yield secured property investment opportunities with fixed net returns.</p><div class="grid sm:grid-cols-2 gap-4 mb-6"><div class="rounded-xl bg-white border border-ink/10 p-6"><div class="font-display text-navy text-3xl mb-1">10%</div><div class="text-xs uppercase tracking-wide text-gold-soft font-semibold mb-4">Fixed Net Return p.a.</div><ul class="space-y-2 text-sm text-ink/70 leading-relaxed"><li>Monthly payments</li><li>Short-term fixed deposit (minimum 6 months)</li><li>Minimum investment $25,000</li><li>No additional fees or costs</li></ul></div><div class="rounded-xl bg-white border border-ink/10 p-6"><div class="font-display text-navy text-3xl mb-1">15%</div><div class="text-xs uppercase tracking-wide text-gold-soft font-semibold mb-4">Fixed Net Return p.a.</div><ul class="space-y-2 text-sm text-ink/70 leading-relaxed"><li>Paid upon project completion</li><li>Short-term project-based deposit (5 to 12 months)</li><li>Secured investment under a registered mortgage</li><li>Minimum investment $100,000</li><li>No additional fees or costs</li></ul></div></div><p class="text-ink/75 leading-relaxed">Clients are encouraged to seek individual legal and financial advice before making any investment decisions.</p></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">6. Use of Licensed Business Partners</h2><p class="text-ink/75 leading-relaxed">During the provision of our services, if Direct Property Buyer does not hold a specific required licence, we will engage our licensed business partners to ensure compliance with all relevant regulations.</p></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">7. Confidentiality</h2><ol class="space-y-3 list-none"><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">7.1</span><span class="text-ink/75 leading-relaxed">We are committed to protecting the confidentiality of our clients&rsquo; information.</span></li><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">7.2</span><span class="text-ink/75 leading-relaxed">Any personal or financial information provided by clients will be used solely for the purpose of providing our services.</span></li></ol></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">8. Limitation of Liability</h2><ol class="space-y-3 list-none"><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">8.1</span><span class="text-ink/75 leading-relaxed">Direct Property Buyer will not be liable for any indirect, incidental, or consequential damages arising from the use of our services.</span></li><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">8.2</span><span class="text-ink/75 leading-relaxed">Our liability is limited to the amount paid by the client for the services provided.</span></li><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">8.3</span><span class="text-ink/75 leading-relaxed">We do not accept responsibility for any loss or damage that is not directly caused by our negligence or breach of contract.</span></li></ol></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">9. Termination</h2><ol class="space-y-3 list-none"><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">9.1</span><span class="text-ink/75 leading-relaxed">We reserve our right to terminate the service agreement with written notice.</span></li><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">9.2</span><span class="text-ink/75 leading-relaxed">Upon termination, clients must settle our outstanding payments (if any).</span></li></ol></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">10. Dispute Resolution</h2><ol class="space-y-3 list-none"><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">10.1</span><span class="text-ink/75 leading-relaxed">Any disputes arising out of or in connection with these terms and conditions shall be resolved through negotiation in good faith.</span></li><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">10.2</span><span class="text-ink/75 leading-relaxed">If the dispute cannot be resolved through negotiation, it shall be referred to mediation administered by the Australian Disputes Centre (ADC) in accordance with the ADC Guidelines for Commercial Mediation.</span></li><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">10.3</span><span class="text-ink/75 leading-relaxed">If mediation fails, the dispute shall be submitted to binding arbitration administered by the ADC, in accordance with the ADC Rules for Domestic Arbitration.</span></li><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">10.4</span><span class="text-ink/75 leading-relaxed">This clause shall survive termination of this agreement.</span></li></ol></div>

<div class="reveal mb-10"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">11. Governing Law</h2><ol class="space-y-3 list-none"><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">11.1</span><span class="text-ink/75 leading-relaxed">These terms and conditions are governed by the laws of Victoria, Australia.</span></li><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">11.2</span><span class="text-ink/75 leading-relaxed">Any unresolved disputes in mediation will be resolved in the courts of Victoria.</span></li></ol></div>

<div class="reveal mb-12"><h2 class="font-display text-navy text-2xl md:text-[1.6rem] mb-4">12. Amendments</h2><ol class="space-y-3 list-none"><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">12.1</span><span class="text-ink/75 leading-relaxed">Direct Property Buyer reserves the right to amend these terms and conditions at any time.</span></li><li class="flex gap-3"><span class="text-gold-soft font-semibold shrink-0">12.2</span><span class="text-ink/75 leading-relaxed">Clients will be notified of any changes via our website.</span></li></ol></div>

<div class="reveal border-t border-ink/10 pt-8"><p class="text-ink/70 leading-relaxed mb-6">If you have any questions about these terms, please get in touch and a member of our team will be happy to help.</p><div class="flex flex-wrap gap-3"><a href="contact.php" data-link class="btn btn-gold">Contact Us</a><a href="index.php" data-link class="btn btn-outline">Back to Home</a></div></div>

</div></section></main>
<?php require __DIR__ . '/includes/footer.php'; ?>