<?php
$page_title       = 'Thank You | Direct Property Buyer';
$page_description = 'Thank you — we have received your enquiry and will be in touch, usually within 12 hours.';
$page_slug        = 'thank-you';
require __DIR__ . '/includes/head.php';
require __DIR__ . '/includes/header.php';
?>
<main id="app"><section class="min-h-[70vh] bg-navy flex items-center relative overflow-hidden"><div class="absolute inset-0 opacity-15"><img src="https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1500&q=80" onerror="this.onerror=null;this.src='https://placehold.co/1200x800/0B1F2A/C49A5A?text=Direct+Property+Buyer'" class="w-full h-full object-cover" alt=""></div><div class="absolute inset-0 bg-gradient-to-b from-navy/90 to-navy"></div><div class="relative max-w-2xl mx-auto px-6 py-24 text-center"><div class="w-16 h-16 mx-auto mb-7 rounded-full bg-gold/15 border border-gold/50 flex items-center justify-center text-gold-soft text-3xl" aria-hidden="true">✓</div><div class="mb-5 flex justify-center"><span class="eyebrow light">Request received</span></div><h1 class="font-display text-white text-4xl md:text-5xl mb-5">Thank you — we have your enquiry.</h1><p class="text-ivory/80 text-lg mb-3">A member of the team will review your details and be in touch, usually within 12 hours.</p><p class="text-ivory/55 text-sm mb-9">There is no obligation at any stage. If you would like to talk sooner, reach us below.</p><div class="flex flex-wrap gap-3 justify-center"><a href="compare-your-options.php" data-link class="btn btn-gold">Explore Your Options</a><a href="property-guides.php" data-link class="btn btn-light">Browse Property Guides</a><a href="https://wa.me/0421300305?text=Hi%20Direct%20Property%20Buyer%2C%20I'd%20like%20a%20free%2C%20no-obligation%20property%20assessment." target="_blank" rel="noopener" class="btn btn-light">Message Us on WhatsApp</a><a href="index.php" data-link class="btn btn-light">Back to Home</a></div></div></section></main>
<?php require __DIR__ . '/includes/footer.php'; ?>
